/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javaswing.view;

import com.javaswing.controle.LivroControle;
import com.javaswing.controle.UsuarioControle;
import com.javaswing.modelo.Livro;
import com.javaswing.modelo.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jorge Lescura
 */
public class EmprestarLivroView extends javax.swing.JFrame {
    private ArrayList<Usuario> listUsuario;
    private ArrayList<Livro> listLivro;
    /**
     * Creates new form LivroConsultarView
     */
    public EmprestarLivroView() {
        initComponents();
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivro = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtConsultar1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLivro1 = new javax.swing.JTable();
        btnConsultar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE USUARIO");
        setSize(new java.awt.Dimension(900, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 48, 63, 27));
        getContentPane().add(txtConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 48, 230, 27));

        tblLivro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Telefone", "Cidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLivro.setGridColor(new java.awt.Color(204, 204, 204));
        tblLivro.setMaximumSize(new java.awt.Dimension(2147483647, 5));
        tblLivro.setPreferredSize(new java.awt.Dimension(700, 300));
        jScrollPane1.setViewportView(tblLivro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 680, 50));

        btnConsultar.setText("Consultar");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        jLabel2.setText("Título");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 63, 27));

        txtConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultar1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, 27));

        tblLivro1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblLivro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Quantidade", "Autor", "Editora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLivro1.setGridColor(new java.awt.Color(204, 204, 204));
        tblLivro1.setMaximumSize(new java.awt.Dimension(2147483647, 5));
        tblLivro1.setPreferredSize(new java.awt.Dimension(700, 300));
        jScrollPane2.setViewportView(tblLivro1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 680, 60));

        btnConsultar1.setText("Consultar");
        btnConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultar1MouseClicked(evt);
            }
        });
        getContentPane().add(btnConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
                
                Usuario usuario = new Usuario();
                usuario.setNome(txtConsultar.getText());
                UsuarioControle usuarioControle = new UsuarioControle();
        try {
            listUsuario = usuarioControle.consultar(usuario);
            this.carregaDadosNaTabela();
        } catch (SQLException ex) {
            Logger.getLogger(EmprestarLivroView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar1MouseClicked

        Livro livro = new Livro();
        livro.setTitulo(txtConsultar.getText());
        LivroControle livroControle = new LivroControle();
        try {
            listLivro = livroControle.consultar(livro);
            this.carregaDadosNaTabela();
        } catch (SQLException ex) {
            Logger.getLogger(LivroConsultarView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultar1MouseClicked

    private void txtConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    private void carregaDadosNaTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tblLivro.getModel();
        
        for(Usuario usuario: listUsuario){
            modelo.addRow(new Object[]{
                usuario.getCodigo(),
                usuario.getNome(),
                usuario.getTelefone(),
                usuario.getCidade(),
                

            });
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLivro;
    private javax.swing.JTable tblLivro1;
    private javax.swing.JTextField txtConsultar;
    private javax.swing.JTextField txtConsultar1;
    // End of variables declaration//GEN-END:variables
}
