/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javaswing.view;

import com.javaswing.controle.EmprestimoControle;
import com.javaswing.controle.LivroControle;
import com.javaswing.controle.UsuarioControle;
import com.javaswing.modelo.Emprestimo;
import com.javaswing.modelo.Livro;
import com.javaswing.modelo.Usuario;
import com.javaswing.service.Util;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jorge Lescura
 */
public class EmprestarLivroView extends javax.swing.JFrame {
    private Usuario usuarioEmprestimo;
    private Livro livroEmprestimo;
    /**
     * Creates new form LivroConsultarView
     */
    public EmprestarLivroView() {
        initComponents();
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNomeLivro = new javax.swing.JTextField();
        btnConsultar1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dataAtual = new javax.swing.JTextField();
        CalculoDevolucao = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtConsultarUsuario = new javax.swing.JTextField();
        txtConsultarLivro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE USUARIO");
        setSize(new java.awt.Dimension(900, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Devoluçao");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 90, 27));
        getContentPane().add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, 27));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        jLabel2.setText("Código Livro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 100, 70, 27));

        txtNomeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeLivroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 230, 27));

        btnConsultar1.setText("Consultar");
        btnConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultar1MouseClicked(evt);
            }
        });
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, -1));

        jLabel3.setText("Nome Livro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 63, 27));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 100, -1));

        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 63, 27));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 80, -1));

        jLabel5.setText("Quantidade");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 63, 27));

        jLabel6.setText("Data Atual");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 63, 27));

        dataAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAtualActionPerformed(evt);
            }
        });
        getContentPane().add(dataAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 80, -1));

        CalculoDevolucao.setText("Calcular");
        CalculoDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculoDevolucaoActionPerformed(evt);
            }
        });
        getContentPane().add(CalculoDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabel7.setText("Código");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 63, 27));
        getContentPane().add(txtConsultarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 40, 27));

        txtConsultarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarLivroActionPerformed(evt);
            }
        });
        getContentPane().add(txtConsultarLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 50, 27));

        jLabel8.setText("Nome");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 63, 27));

        jButton1.setText("Emprestar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar1MouseClicked
        LivroControle livroControle = new LivroControle();
        UsuarioControle usuarioControle = new UsuarioControle();
        
        Usuario usuarioEmprestimo = new Usuario();
        Livro livroEmprestimo = new Livro();
        
        livroEmprestimo.setCodigo(Integer.parseInt(txtConsultarLivro.getText()));
        usuarioEmprestimo.setCodigo(Integer.parseInt(txtConsultarUsuario.getText()));
        
        
       try {
            livroEmprestimo = livroControle.consultarCodigo(livroEmprestimo);
            usuarioEmprestimo = usuarioControle.consultarCodigo(usuarioEmprestimo);
        } catch (SQLException ex) {
            Logger.getLogger(EmprestarLivroView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        txtNomeUsuario.setText(usuarioEmprestimo.getNome());
        txtNomeLivro.setText(livroEmprestimo.getTitulo());
        jTextField1.setText(String.valueOf(livroEmprestimo.getQuantidade()));
       
        if(usuarioEmprestimo.getTipo() == 1 ){
            jTextField2.setText("Professor");
        }else if(usuarioEmprestimo.getTipo() == 2){
            jTextField2.setText("Aluno");
        }else if(usuarioEmprestimo.getTipo() == 3){
            jTextField2.setText("Funcionário");
        }else{
             jTextField2.setText("null");
        }
        

        
        
    }//GEN-LAST:event_btnConsultar1MouseClicked

    private void txtNomeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeLivroActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void dataAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAtualActionPerformed

    private void CalculoDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculoDevolucaoActionPerformed
        UsuarioControle usuarioControle = new UsuarioControle();
        Usuario usuarioEmprestimo = new Usuario(); 
        Util devolucao = new Util();
        String dataDevolucao = null;
        Date dataSaida = null;
        
        usuarioEmprestimo.setCodigo(Integer.parseInt(txtConsultarUsuario.getText()));
        
        try {
            usuarioEmprestimo = usuarioControle.consultarCodigo(usuarioEmprestimo);
            dataSaida = devolucao.stringToDate(dataAtual.getText());
            dataDevolucao = devolucao.calcularDevolucao(dataSaida,usuarioEmprestimo.getTipo());
        } catch (SQLException ex) {
            Logger.getLogger(LivroExcluirView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(EmprestarLivroView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextField3.setText(dataDevolucao);
                
    }//GEN-LAST:event_CalculoDevolucaoActionPerformed

    private void txtConsultarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultarLivroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EmprestimoControle emprestimoControle = new EmprestimoControle();
        Emprestimo emprestimo = new Emprestimo();
        Util util = new Util();
        
        UsuarioControle usuarioControle = new UsuarioControle();
        Usuario usuarioEmprestimo = new Usuario();
        
        LivroControle livroControle = new LivroControle();
        Livro livroEmprestimo = new Livro();
        
        livroEmprestimo.setCodigo(Integer.parseInt(txtConsultarLivro.getText()));
        
        try {
            usuarioEmprestimo = usuarioControle.consultarCodigo(usuarioEmprestimo);
            livroEmprestimo = livroControle.consultarCodigo(livroEmprestimo);
        } catch (SQLException ex) {
            Logger.getLogger(EmprestarLivroView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int codUsuario = Integer.parseInt(txtConsultarUsuario.getText());
        int codLivro = Integer.parseInt(txtConsultarLivro.getText());
        String dataSaida = dataAtual.getText();
        String dataDevolucao = jTextField3.getText();
        Date saidaDate = null;
        try {
            saidaDate = util.stringToDate(dataSaida);
        } catch (ParseException ex) {
            Logger.getLogger(EmprestarLivroView.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
        int status = usuarioEmprestimo.getTipo();
        String dataDevolucao = util.calcularDevolucao(saidaDate, status);
        */

        
        emprestimo.setCodUsuario(codUsuario);
        emprestimo.setCodLivro(codLivro);
        emprestimo.setDataAtualString(dataSaida);
        emprestimo.setDataDevolucaoString(dataDevolucao);
        
        
        try {
            if(emprestimoControle.emprestarLivro(emprestimo) == true){
                JOptionPane.showMessageDialog(null,"Livro emprestado com sucesso!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"ERRO; Livro não emprestado !","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioCadastrarView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Integer novaQuantidade = livroEmprestimo.getQuantidade()-1;
        livroEmprestimo.setQuantidade(novaQuantidade);
        try {
            livroControle.atualizar(livroEmprestimo);
        } catch (SQLException ex) {
            Logger.getLogger(EmprestarLivroView.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculoDevolucao;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField dataAtual;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtConsultarLivro;
    private javax.swing.JTextField txtConsultarUsuario;
    private javax.swing.JTextField txtNomeLivro;
    private javax.swing.JTextField txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
